'USE STRICT'

function convertirLitrosaCentilitros(Litros){
let resultado = Litros *100; 

return resultado ;
console.log ("litros a centilitros=" +resultado)

}






let NUMERO1 = 50 ;
let NUMERO2 = 4 ;
resultado = NUMERO1 + NUMERO2;
console.log ("SUMA=" +resultado);
resultado = NUMERO1 - NUMERO2;
console.log ("RESTA=" +resultado);
resultado = NUMERO1 * NUMERO2;
console.log ("MULTIPLICACION=" +resultado);
resultado = NUMERO1 / NUMERO2;
console.log ("DIVISION=" +resultado);
